import type { Metadata } from "next";
import { Kalnia, Lato } from "next/font/google"
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const kalnia = Kalnia({ subsets: ['latin'] })
export const lato = Lato({ weight: ["400"], subsets: ['latin']})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={kalnia.className}>
        {children}
      </body>
    </html>
  );
}
